// <auto-generated />
using System;
using AutoMapperEFCore.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoMapperEFCore.Model.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20210906064602_2021.9.6-01")]
    partial class _20219601
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutoMapperEFCore.Model.StudentInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnName("AGE");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnName("BIRTHDAY");

                    b.Property<string>("Gender")
                        .HasColumnName("GENDER");

                    b.Property<string>("Name")
                        .HasColumnName("NAME");

                    b.HasKey("ID");

                    b.ToTable("STUDENTINFO");
                });
#pragma warning restore 612, 618
        }
    }
}
